name: End-to-end Tests
on:
  push:
   branches:
     - master
  schedule:
      - cron: '30 16 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn 
          start: yarn open
          browser: chrome
