name: End-to-end Tests
on:
  push:
    path:
      - '!README.md'
      - '**.cy.js'
    branches:
     - master
  workflow_dispatch:   
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn 
          start: yarn open
          browser: chrome
          config-file: cypress.config.js
          headed: true
      - name: Upload artifact to enable deployment
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: docs
